### ISSUE TITLE
[Feature Request] Support filters, sort and pagination for Get()

### ISSUE THREAD

**Issue by Bnaya** [nestjsx/crud#2]
A common need is to filter the entires returned by rest list, and to paginate over them.
It will be very use-full to have a build-in way to do it

**Comment by zMotivat0r** [comment]
@Bnaya Roger that! Will add it to the Roadmap. Thanks!

**Comment by NaturesProphet** [comment]
[Nest] 7036   - 2018-7-9 22:12:55   [ExceptionHandler] Nest cannot create the module instance. Often, this is because of a circular dependency between modules. Use forwardRef() to avoid it. (Read more https://docs.nestjs.com/advanced/circular-dependency.) Scope [AppModule]
Error: Nest cannot create the module instance. Often, this is because of a circular dependency between modules. Use forwardRef() to avoid it. (Read more https://docs.nestjs.com/advanced/circular-dependency.) Scope [AppModule]

here is the module:
import { Module } from '@nestjs/common';
import { TypeOrmModule } from '@nestjs/typeorm';
import { E_usuario } from '../models/E_usuario';
import { UserServices } from '../services/User.services';
import { UserController } from '../controllers/User.controller';

@Module( {
    imports: [ TypeOrmModule.forFeature( [ E_usuario ] ) ],
    providers: [ UserServices ],
    controllers: [ UserController ],
} )
export class CatsModule { }

**Comment by zMotivat0r** [comment]
@Bnaya Hope, it will be released this week with what you've requested and a lot of other handy stuff.

**Comment by zMotivat0r** [comment]
@Bnaya done. Please try the new version.

**Comment by Bnaya** [comment]
Thank you very much!
I hope i will have time soon to do so! :)
