### ISSUE TITLE
When are you planning to release next version?

### ISSUE THREAD

**Issue by VLZH** [nestjsx/crud#296]
In last time you merge very important features / fixes for me. I would be happy to see next minor release in npm.

**Comment by zMotivat0r** [comment]
Very soon, my friend. A couple of things are left.

**Comment by binarytracer** [comment]
hi @zMotivat0r , im excited also on this one, hoping initial resources should have pagination info.

**Comment by VLZH** [comment]
@zMotivat0r Thank you for alpha release!

**Comment by njournaud** [comment]
Hi guys, thank you for the library !
I come back to you to know when you will release the 4.3.0 . 
I really need the CrudAuth feature!

Thank you again

**Comment by noneedinmagic** [comment]
Hello! Asking the same question. We are developing new project and first MVP should be released in December. Right now I'm in between two options:
1. Just override methods in almost every controller to achieve CrudAuth-like behavior
2. Use new alpha hoping it will get to release in this month and then update.
I cannot wait to implement these features because it stops frontender's work in my team.

Also there is an issue with "or" param overriding any auth conditions cause or and/or operators priority in SQL. Right now I need to clear any "or" arguments while overriding controller methods. And it is not clear from the issues page here if it will be fixed in the next release or not.

So are there any estimates? Maybe, we can help somehow to bring it faster? 😅

Thanks!

**Comment by zMotivat0r** [comment]
I just started the final round of this update. Some small bugs left and the main and more painful part is the documentation. If I'll manage to finish it tomorrow, then I'll release it tomorrow. If no, then it'll be Monday-Tuesday in case there won't be any surprises.

**Comment by binarytracer** [comment]
@noneedinmagic @zMotivat0r im currently interested on this approach also. @zMotivat0r Ive chatted this thing to you last week. basically im currently considering to use decorators here or extending this method, [here](https://github.com/nestjsx/crud/blob/master/packages/crud-typeorm/src/typeorm-crud.service.ts#L232)

What do you think, guys?
