### ISSUE TITLE
Is it mistake?

### ISSUE THREAD

**Issue by VLZH** [nestjsx/crud#301]
https://github.com/nestjsx/crud/blob/master/packages/crud-typeorm/src/typeorm-crud.service.ts#L151-L154
I think this conditional is inconsistent with wiki.

**Comment by zMotivat0r** [comment]
No there is no mistake.
So basically, if `allowParamsOverride: true`, then the property that is in the DTO will be saved. If it's `false`, then we override props that are in the DTO by the params values to keep those props unchanged and protected for any changes that come from the DTO values.
Maybe I just need to change that part of the wiki, because now I see that it might be confusing.

**Comment by VLZH** [comment]
@zMotivat0r Yeea, this point in wiki actually confuse me
