### ISSUE TITLE
Return paginate results with 206 HTTP status

### ISSUE THREAD

**Issue by njournaud** [nestjsx/crud#320]
Hello guys,

Just  to know why you'r not using HTTP code 206 Partial Content in return for a paged result ?

Thank you.

**Comment by Darkein** [comment]
HTTP 206 is used when you only want a part of your asked data, using a 'range request'.
For exemple when you want to download a big file, you could want to download multiple parts of it instead of download everything. You will ask a range of bytes of your file when you call your api (with the 'Content-Range' header), which will return your chunked data.

In case of a paged result, you don't want a part of expected data but a complete result, but this result is filtered using some params (count by page, current page, etc...)

You can find more info on http 206 code on MDN: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/206
