### ISSUE TITLE
CrudAuth unexpected behavior with filter params

### ISSUE THREAD

**Issue by DaVarga** [nestjsx/crud#323]
Hi @zMotivat0r ,

I have a table of books that uses CrudAuth to filter by bookstore:

```
@CrudAuth({
  filter: (user: User) => ({
    storeId: user.store.id,
  }),
  persist: (user: User) => ({
    storeId: user.store.id,
  }),
})

```
When I make a query like this:

/books?filter=title||cont||Quijote&or=author||cont||Cervantes

It returns all books of the store, not only Quijote. The resulting SQL query adds a WHERE like this:
```
WHERE (Book.storeId = ?) OR `Book`.`title` LIKE ? OR `Book`.`author` LIKE ? -- PARAMETERS: [1,"%Quijote%","%Cervantes%"]
```
As you can see the separation between the auth parameter and the others is made with an OR, but I was specting an AND, as I suppose authentication is always an extrict filter. Is an OR the expected behavior?

If I don't use an OR in the REST call (not adding the author filter), then it uses an AND as expected.

Thanks for your work!

_Originally posted by @kereslas in https://github.com/nestjsx/crud/pull/302#issuecomment-548628063_

**Comment by kereslas** [comment]
Thanks @DaVarga for posting here. This is the correct place, not where I put it originally.

**Comment by DaVarga** [comment]
Hey @kereslas,
did you already try the new search parameter? (#265) In my case it works with an OR operator and CrudAuth

**Comment by kereslas** [comment]
Hi @DaVarga ,

I have not tried with new search parameter. I have made a modification to TypeOrmCrudService that, at least for my use case, seems to fix this. You can see more on PR up.

For using the PR, as it is not in master branch until review, I have created a new file in my project with PR contents (its only one file). In this file, I have changed class name to MyTypeOrmCrudService. Then I can use this class instead of the default in my CRUD services.

**Comment by kereslas** [comment]
Hi @DaVarga,

You can close this issue, as PR #327 has been merged on master branch with a fix.

Thanks!
