### ISSUE TITLE
Update documentation to make clear that MongoDB is not supported directly through TypeORM or any other  mechanism

### ISSUE THREAD

**Issue by bastibense** [nestjsx/crud#358]
Maybe someone should update the docs to tell newcomers that MongoDB is not directly supported. I spend an hour setting up a prototype app only to run right into the wall with message that MongoDB is not supported by the CRUD utils.

I find it confusing that both Nest.js and this CRUD docs tell everyone that everything is "database agnostic" and even MongoDB is mentioned a couple of time as supported. While that might be true for manual handling of requests through Nest (via mongoose or maybe even TypeORM), the CRUD package apparently builds ontop of a query builder that is not up to the task.

**Comment by zMotivat0r** [comment]
> Maybe someone should update the docs to tell newcomers that MongoDB is not directly supported. I spend an hour setting up a prototype app only to run right into the wall with message that MongoDB is not supported by the CRUD utils.
> 
> I find it confusing that both Nest.js and this CRUD docs tell everyone that everything is "database agnostic" and even MongoDB is mentioned a couple of time as supported. While that might be true for manual handling of requests through Nest (via mongoose or maybe even TypeORM), the CRUD package apparently builds ontop of a query builder that is not up to the task.

Hi. Thanks for your comment. I'll add the note to the docs that TypeOrm package is using query building. A agree that this information will help newcomers.

There is no a single please in this package that says everything is database agnostic. It says that controllers are. And it's totally true. Also, it would be super nice if you could show me those places where it says that MongoDB is supported - I'll fix them too, because I don't remember that I ever put this information.

Thanks again!

**Comment by zMotivat0r** [comment]
updated
