### ISSUE TITLE
AfterUpdate not working in entity.ts

### ISSUE THREAD

**Issue by sandeshgb** [nestjsx/crud#386]
I want to execute a certain code-section after my data has been updated. I tried AfterUpdate decorative in my entity.ts file but its not working. When I added a console it wasn't getting printed, stating the function is never called. The update I'm doing is through nestjs crud i.e patch request.

Ex: Consider table users_addresses. Assume its has following fields: id(integer), user_id(integer), name(string), is_primary(boolean).
Now whenever user adds or updates an address as primary we have to first check into database if there exist any other primary address, if yes then set its value as false and make current as true(primary).

I also tried using using subscriber but no success. Kindly assist.

Version details:
nest: 6.10.4
package.json:
"@nestjs/typeorm": "^6.2.0"
"@nestjsx/crud": "^4.2.0",
"@nestjsx/crud-typeorm": "^4.2.0"
"typeorm": "^0.2.20"

**Comment by zMotivat0r** [comment]
@sandeshgb I wonder why you don't use the latest version?

**Comment by sandeshgb** [comment]
@zMotivat0r can you guide me on what should I update and to which version.
Also once updated to new versions how will the code be.

I tried https://typeorm.io/#/listeners-and-subscribers/afterupdate
This as well, https://github.com/nestjs/typeorm/pull/27

**Comment by zMotivat0r** [comment]
the latest crud lib version in [4.4.1](https://github.com/nestjsx/crud/releases/tag/v4.4.1)
But please keep in mind that crud-typeorm package uses `save` method for updating an entity. 
https://github.com/nestjsx/crud/blob/ded1845ffd92d3dda9bbb49248b334a2b5ea7ff0/packages/crud-typeorm/src/typeorm-crud.service.ts#L164
That's because we wanna make sure that relational data that might come in the request body will be saved/updated too. There was a discussion here around that and AFAIK TypeORM still doesn't support updating relation data on `update` method

**Comment by hakimio** [comment]
@zMotivat0r even when using the latest version of crud lib "beforeUpdate" events are not invoked when doing `updateOne()` / PATCH entity/1.

**Comment by hakimio** [comment]
Ok, sorry for confusion, it's a TypeORM thing. It doesn't fire `BeforeUpdate` event when relationship (OneToMany/ManyToMany) is updated. CRUD library is fine. This issue can be closed.
