### ISSUE TITLE
CrudValidationGroups isn't working for custom DTO classes

### ISSUE THREAD

**Issue by y-moroz** [nestjsx/crud#457]
Hi, first of all, thanks for such a good library.

I want to use one DTO both for create and update routes, but to have all properties to be optional for update route. So here is simplified version of my code:
```typescript
class CreateUserDto {
  @IsOptional({groups: [CrudValidationGroups.UPDATE]})
  @IsNumber()
  age: number;

  @IsOptional({groups: [CrudValidationGroups.UPDATE]})
  @IsDateString()
  birthDate: string;
}

@Crud({
  dto: {
    create: CreateUserDto,
    update: CreateUserDto,
  }
})
export class UserController implements CrudController<UserEntity>  {
  constructor(public service: UserService) {}
}
```

But according to https://github.com/nestjsx/crud/blob/master/packages/crud/src/crud/crud-routes.factory.ts#L425 validation group will be `undefined` if custom DTO class was passed. What the reason for this? Why validation groups cannot be passed for custom DTO classes?

**Comment by zMotivat0r** [comment]
Hi, the reason for that is pretty simple and thus seems very obvious to me: when you pass a DTO for `create`  there is no need to pass groups because it's just one create operation. Same for an update operation.
Also, you're saying:
>I want to use one DTO both for create and update routes, but to have all properties to be optional for update route. 

that exactly the reason why the lib initially has the [request validation](https://github.com/nestjsx/crud/wiki/Controllers#request-validation) approach. Why don't you use it?

**Comment by y-moroz** [comment]
@zMotivat0r thanks for your answer.

As I understand in the request validation approach I should use one model for CREATE, UPDATE and GET routes. But there are fields that should be presented only in the GET route response (`id` for example). To pass the validation, in this case, we can use `@IsOptional({ groups: [UPDATE, CREATE] })`, but in the Swagger schema the field will be presented, and there is no way to conditionally show/hide fields in the Swagger schema.

**Comment by zMotivat0r** [comment]
>As I understand in the request validation approach I should use one model for CREATE, UPDATE and GET routes.

There is no validation for GET routes because in GET you don't pass body for the obvious reason.

>But there are fields that should be presented only in the GET route response

This has nothing to do with the request validation. It's a serialization responsibility ([docs](https://github.com/nestjsx/crud/wiki/Controllers#serialize)). So, you just need to pass a serialization class to the `serialize: { get: YourGetResponseDto }`

**Comment by y-moroz** [comment]
Cool, thanks for your help.
