### ISSUE TITLE
required=true should add the join in the query

### ISSUE THREAD

**Issue by jbrousseau** [nestjsx/crud#483]
**Steps to reproduce **

Here is my controller:

```
@Controller('/company/{company_id}/posts')
@Crud({
    model: {
        type: PostEntity
    },
    params: {
        company_id: {
            field: 'user.company_id',
            type: 'number'
        },
    },
   query: {
        join: {
            user: {
                alias: 'user',
                required: true
            },
        }
    },
export class PostsController implements CrudController<PostEntity> {
[...]
```

GET `/company/{company_id}/posts` failed because the user table is not included in the query, despite I put `required` parameter to true.

I have to add `eager: true` to have the join, which doesn't make sense in my case because I don't want to persist all the content of the user in the GET response.

**Comment by zMotivat0r** [comment]
Hi,

>required=true should add the join in the query

no, it should not.

[Wiki](https://github.com/nestjsx/crud/wiki/Controllers#join) says:

>require - should a relation be required or not. For RMDBS means use either INNER or LEFT join. Default: false.

and because of this

>An Object of relations that allowed to be fetched by passing join query parameter in GET requests.

all relationships except those that are marked as `eager: true` should be requested in the query params explicitly. 

If you wanna join a relationship but don't wanna have this related object in the response, you can use a [response serialization](https://github.com/nestjsx/crud/wiki/Controllers#response-serialization) for now.

A feature of joining related entities but not include them in the response will be added in the upcoming releases. We already have issues created.
