### ISSUE TITLE
How to use a crud-typeorm service in another module

### ISSUE THREAD

**Issue by elaijuh** [nestjsx/crud#507]
Since the `repo` in the service is protected, it's not good to public it. And there is no specific wifi explains how to reuse the service in another module. I would like to know the best practice of doing this. Thanks.

**Comment by zMotivat0r** [comment]
Hi, sorry for the delayed response.
Crud services intend to be used in the crud controller since its crud methods tightly depend on the parsed request and controllers' options, especially for a particular route/action.
We had a similar discussion here earlier.
This is my reply to it https://github.com/nestjsx/crud/issues/459#issuecomment-611889656

And here are some simple methods that each crud service has:
https://github.com/nestjsx/crud/blob/115ee2b5e315ea2869af886e4c2e3a5f7ad0b0e9/packages/crud-typeorm/src/typeorm-crud.service.ts#L73-L83
So, you can easily extend it with your own methods and thus use them in another services/controllers/modules.
Cheers!
