### ISSUE TITLE
getMany() 如果请求的filter参数不在实体中 报错

### ISSUE THREAD

**Issue by crismcn** [nestjsx/crud#519]
getMany()方法 如果请求的条件 filter 含不在实体中的字段会报错，如何限制请求参数呢
{
    "message": "ER_BAD_FIELD_ERROR: Unknown column 'QuestionEntity.na2e' in 'where clause'",
    "status": 500,
    "path": "/api/v1/question?filter=na2e%7C%7Ccont%7C%7C3"
}

**Comment by zMotivat0r** [comment]
In English, please

**Comment by gnbertiz08** [comment]
I have same problem.

`
@Crud({
    model: {
        type: Tours
    },
})
@Controller('tours')
export class ToursController  {
    constructor(public toursService: ToursService) {
    }
}
`
![nestjscrud](https://user-images.githubusercontent.com/37982459/82552554-e5bc2800-9b94-11ea-8678-68fcbf3a1d0d.PNG)

**Comment by zMotivat0r** [comment]
@gnbertiz08 I have to notice that your error is not the same. It says that it can't find `getMany` of undefined which means you have something wrong with your enitity import or something like that because a framework can't find your entity that's why it's undefined. 
I suggest you check your feature module entities imports.
@crismcn please, describe your problem in English and add more information on your entity and controller
