### ISSUE TITLE
filter param generator helper

### ISSUE THREAD

**Issue by Bnaya** [nestjsx/crud#53]
Is there any ready-made lib that will take query object, in a syntax similar to, say mongo  query,
And will give the appropriate `filter` for it?
![Screen Shot 2019-03-29 at 18 22 25](https://user-images.githubusercontent.com/1304862/55243143-ab385300-524f-11e9-9531-c4d7154f4863.png)
The syntax is very hard to write

**Comment by zMotivat0r** [comment]
Why do we need any such library if we can create a query builder for current implementation? And there will not be any breaking changes.

**Comment by Bnaya** [comment]
To clarify: 
I'm writing the client side, (react-admin dataProvider to be more specific)
And my input is javascript object, and i need to build complex query param filter from it.

If i had mongo-like query api that would much simpler for me

**Comment by esistgut** [comment]
@Bnaya did you make any progress on the react-admin data provider?

**Comment by Bnaya** [comment]
I wrote something sketchy,
That im using since then,
But 2 days ago i also found that new provider
I will maybe refactor to use it.
I will be happy to hear how it was for you

**Comment by zMotivat0r** [comment]
@Bnaya @esistgut 
I've made a package `@nestjsx/request-query` (haven't published it yet though). It's framework agnostic and can be used on both - frontend and backend. It will be used in our `RestfulQueryInterceptor` on `GET` requests as well. The usage example (frontend):
```typescript
import { RequestQueryBuilder } from '@nestjsx/request-query';

const qb = new RequestQueryBuilder();

const queryString = qb
  .select(['id', 'name', 'email'])
  .setFilter({ field: 'name', operator: 'eq', value: 'John' })
  .setOr({ field: 'email', operator: 'cont', value: 'john' })
  .setJoin({ field: 'company', select: ['name'] })
  .setJoin({ field: 'profile' })
  .sortBy({ field: 'id', order: 'DESC' })
  .setLimit(20)
  .setPage(3)
  .resetCache()
  .query();
```
Also, it will be possible to set names map to each of existing query param, .e.g:

```typescript
import { RequestQueryBuilder } from '@nestjsx/request-query';

RequestQueryBuilder.setOptions({
  delim: '||',
  delimStr: ',',
  paramNamesMap: {
    fields: ['fields', 'select'],
    filter: ['filter[]', 'filter'],
    or: ['or[]', 'or'],
    join: ['join[]', 'join'],
    sort: ['sort[]', 'sort'],
    limit: ['per_page', 'limit'],
    offset: ['offset'],
    page: ['page'],
    cache: ['cache'],
  },
})
```
...and to change to whatever you want. And of coucre this must be done on the backend side as well. I'll provide more details on that in the future.
Also, there won't be a need in `class-validator` to validate query param anymore, because I've added all validation needed and it's reusable on both - frontend and backend.

So guys, please let me know what you think about that. It's 100% done, 100% covered by tests, but not published yet.

Cheers!

**Comment by Bnaya** [comment]
Amazing, thank you!!

**Comment by zMotivat0r** [comment]
@Bnaya please see the [docs](https://github.com/nestjsx/crud/wiki/Requests#frontend-usage)
