### ISSUE TITLE
Eager relations

### ISSUE THREAD

**Issue by avatsaev** [nestjsx/crud#67]
There is no option in the services or controller to specify eager relations? (include eager relations by default without specifying `join` in the query params?)

**Comment by Bnaya** [comment]
See #54 
What i did is to override (getOne) and inject query params

Example:
```

@Crud(Brand, {
  params: {
    id: "string",
  },
  options: {
    limit: 100,
    join: {
      categories: {
        allow: [],
      },
    },
  },
})
@Controller("api/brands")
export class BrandsController {
  constructor(public service: BrandsService) {}

  private get base(): CrudController<BrandsService, Brand> {
    return this;
  }

  @Override()
  public async getOne(@ParsedQuery() query: any, @ParsedOptions() options: any) {
    if (this.base.getOneBase) {
      if (!Array.isArray(query.join)) {
        query.join = [];
      }

      query.join.push({
        field: "categories",
        select: [],
      });

      return this.base.getOneBase(query, options);
    }
  }
}

```

**Comment by fwoelffel** [comment]
That is because this library relies on TypeORM's `QueryBuilder` to perform its queries against the database. This said query builder doesn't care about the `eager` metadata. I don't see how the `eager` keyword could be supported for now.

Reference: https://typeorm.io/#/eager-and-lazy-relations/eager-relations

**Comment by zMotivat0r** [comment]
@avatsaev @Bnaya @fwoelffel please see the [docs](https://github.com/nestjsx/crud/wiki/Controllers#join)
